/*!
 * \file    resource.hpp
 * \date    Sat Aug 17 02:19:09 2013
 * \warning This file is automatically generate by srg.
 *          DO NOT EDIT THIS FILE.
 */

#ifndef SRG_RESOURCE_HPP
#define SRG_RESOURCE_HPP

enum RESOURCE_TABLE {
  IMAGE0 = 0x0000U,
  IMAGE2 = 0x0001U,
  IMAGE3 = 0x0002U,
  MUSIC0 = 0x0003U,
  MUSIC1 = 0x0004U,
  SOUND0 = 0x0005U,
  SOUND1 = 0x0006U,
  NUM_ASSETS = 7
};

#endif

