###
### Template Makefile
### 

### Set SaC2 make directory path, if NOT defined yet
SAC_MAKE ?= ../../make/rules.mk

### Name of the application
EXEC     = SaCDemo

### Specify the compilator
CXX      = g++

### Extra compilation options
CXXFLAGS = -DSAC2_LOGGER_ENABLED

### The following line is required to compile SaC2 source files
include $(SAC_MAKE)
