/*!
 * \file    resource.hpp
 * \date    Thu Jun 27 04:24:38 2013
 * \warning This file is automatically generate by srg.
 *          DO NOT EDIT THIS FILE.
 */

#ifndef SRG_RESOURCE_HPP
#define SRG_RESOURCE_HPP

enum RESOURCE_TABLE {
  IM0001 = 0x0000U,
  IM0002 = 0x0001U,
  SD0001 = 0x0002U,
  NUM_ASSETS = 3
};

#endif

