###
### Template Makefile
### 

### Set the SAC_MAKE directory path, if it is NOT defined yet
SAC_MAKE ?= ../make/rules.mk

### Name of the application
EXEC     = SaCDemo

### Extra compilation options
CXXFLAGS = -DLOG_ENABLED  #allow log file generation

### The following line is required to compile SaC2 source files
include $(SAC_MAKE)
