
RESOURCE_FILE = resource.xml
MEMCHECK_FLAGS += --log-file=demo.log \
                  --read-var-info=yes \
                  --leak-check=full \
                  --track-origins=yes

include $(SAC2_MAKERULES)
