/*!
 * \file resource.hpp
 * \date Sun May  4 19:36:06 2014
 * \warning This file is automatically generate by `srg''.
 * DO NOT EDIT THIS FILE.
 */

#ifndef SRG_RESOURCE_HPP
#define SRG_RESOURCE_HPP

enum RESOURCE_TABLE {
 C001 = 0x0000U,
 NUM_ASSETS = 1
};

#endif

