/*!
 * \file    resource.hpp
 * \date    Thu Jun 27 23:40:52 2013
 * \warning This file is automatically generate by srg.
 *          DO NOT EDIT THIS FILE.
 */

#ifndef SRG_RESOURCE_HPP
#define SRG_RESOURCE_HPP

enum RESOURCE_TABLE {
  BALL = 0x0000U,
  NUM_ASSETS = 1
};

#endif

