/*!
 * \file resource.cpp
 * \date Sun May  4 19:36:06 2014
 * \warning This file is automatically generate by `srg''.
 * DO NOT EDIT THIS FILE.
 */

#include <sac2_asset_manager.hpp>
#include "resource.hpp"

namespace sac2
{

const AssetManager::asset_map_t AssetManager::m_asset_table =
{
 {(asset_id_t) C001, "test_character.png"}
};

}

